title: Tutoring
markdown: kramdown
kramdown:
  math_engine: mathjax
  math_engine_opts:
    preview: false
  parse_block_html: true
  syntax_highlighter_opts:
    disable: true
  math_delimiters: dollar
